kind: Secret
apiVersion: v1
metadata:
  name: postgresql-credentials
  namespace: databases
type: Opaque
data:
  postgresql-password: <path:local-development-cvops#postgresql-password | base64encode>
  postgresql-username: <path:local-development-cvops#postgresql-username | base64encode>