apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: cvez
  labels:
    app: monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: localhost:32000/monitor:test
---
# Create kubenetes namespace called cvez
apiVersion: v1
kind: Namespace
metadata:
  name: cvez
  labels:
    name: cvez
