kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.6/install.yaml
  - database-setup.yaml
  - artifact-secret.yaml
  - postgresql-credentials.yaml

patchesStrategicMerge:
  - init-containers.yaml