kind: Secret
apiVersion: v1
metadata:
  name: argo-postgres-config
  namespace: argo-workflows
type: Opaque
data:
  password: <path:local-development-cvops#argo-db-password | base64encode>
  username: <path:local-development-cvops#argo-db-username | base64encode>