# Default values for cvops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

spec:
  destination:
    server: in-cluster
  source:
    repoURL: git@github.com:kevin-presalytics/cvops-hub-deployment.git
    targetRevision: main
    kustomize:
      version: v4.5.7
  