apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.0-rc1/manifests/install.yaml

patchesStrategicMerge:
- argocd-repo-server-deploy.yaml
- argocd-cm.yaml

secretGenerator:
  - name: argocd-vault-plugin-credentials
    envs:
    - argocd-vault-plugin-credentials.env

generatorOptions:
  disableNameSuffixHash: true