apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-workflows
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: argo-workflows
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
