apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emqx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mqtt
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://github.com/emqx/emqx.git
    targetRevision: master
    path: deploy/charts/emqx
    helm:
      valueFiles:
      - $values/mqtt/emqx/local-values.yaml
      parameters:
      - name: "ingress.mqtt.hosts"
        value: "{mqtt.{{ .Values.domain }}}"
      - name: "image.tag"
        value: "5.0.24"
  - repoURL: {{ .Values.spec.source.repoURL }}
    ref: values
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: mqtt/emqx/secrets
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
