apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cvops
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: hub
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: helm_values
        value: |
          domain: {{ .Values.domain }}
          secretStore:
            name: {{ .Values.secretStore.name }}
            type: azureKeyVault
          mqtt:
            adminUsername: <path:{{ .Values.secretStore.name }}#mqtt-api-key>
            adminPassword: <path:{{ .Values.secretStore.name }}#mqtt-api-secret>
          postgresql:
            password: <path:{{ .Values.secretStore.name }}#postgresql-password>
          storage:
            key: <path:{{ .Values.secretStore.name }}#minio-root-user>
            secret: <path:{{ .Values.secretStore.name }}#minio-root-password>
          influxdb:
            user: <path:{{ .Values.secretStore.name }}#influxdb-user>
            password: <path:{{ .Values.secretStore.name }}#influxdb-password>
          hub:
            auth:
              oidc:
                redirectUri: https://{{ .Values.domain }}/oidc-callback/
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
