apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cvops
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: hub
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: helm_values
        value: |
          domain: {{ .Values.domain }}
          secretStore:
            name: {{ .Values.secretStore.name }}
            type: azureKeyVault
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
