apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: storage
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://charts.min.io/
    targetRevision: 5.0.7
    chart: minio
    helm:
      releaseName: minio
      valueFiles:
      - $values/minio/local-values.yaml
  - repoURL: {{ .Values.spec.source.repoURL }}
    ref: values
    targetRevision: {{ .Values.spec.source.targetRevision }}
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: minio/secrets
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  plugin:
    name: argocd-vault-plugin
