apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cvops
    server: {{ .Values.spec.destination.server }}
  project: cvops
  source:
    path: monitor
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}