apiVersion: v1
kind: Namespace
metadata:
  name: cvops
  labels:
    name: cvops
---
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
  labels:
    name: mqtt
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases
