apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: databases
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://charts.timescale.com/
    targetRevision: 0.33.1
    chart: timesacledb-single
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: helm_values
        value: |
          replicaCount: 1
          secrets:
            credentials:
              PATRONI_SUPERUSER_PASSWORD: <path:{{ .Values.secretStore.name }}#postgresql-password>
              PATRONI_REPLICATION_PASSWORD: <path:{{ .Values.secretStore.name }}#postgresql-password>
              PATRONI_admin_PASSWORD: <path:{{ .Values.secretStore.name }}#postgresql-password>

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: true
