apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: databases
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.7
    chart: postgresql
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: helm_values
        value: |
          auth:
            postgresPassword: <path:{{ .Values.secretStore.name }}#postgresql-password>

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: true
