apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: databases
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.7
    chart: postgresql
    helm:
      releaseName: postgresql
      valueFiles:
      - $values/postgresql/local-values.yaml
  - repoURL: {{ .Values.spec.source.repoURL }}
    ref: values
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
