apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvops-hub-ui
  labels:
    name: cvops-hub-ui
spec:
  rules:
  - host: app.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cvops-hub-ui
            port: 
              number: 80
