apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  labels:
    name: ui
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: app.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ui
            port: 
              number: 80
