kind: Secret
apiVersion: v1
metadata:
  name: hub
type: Opaque
data:
  postgresql__password: {{ .Values.postgresql.password | base64encode }}
  mqtt__adminUsername: {{ .Values.mqtt.adminUsername | base64encode }}
  mqtt__adminPassword: {{ .Values.mqtt.adminPassword | base64encode }}
  storage__key: {{ .Values.storage.key | base64encode }}
  storage__secret: {{ .Values.storage.secret | base64encode }}
  influxdb__user: {{ .Values.influxdb.user | base64encode }}
  influxdb__password: {{ .Values.influxdb.password | base64encode }}