apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
spec:
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      serviceAccountName: cvops-hub
      volumes:
        - name: appsettings
          configMap:
            name: cvops-appsettings
            items:
              - key: appsettings.yaml
                path: appsettings.yaml
      {{- if not (or (eq .Values.hub.api.debugMode true) (eq .Values.hub.dbMigrations.debugMode true)) }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- end }}
      containers:
      - name: hub
        image: {{ .Values.hub.api.image }}
        command: ["dotnet", "api.dll"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "125m"
        volumeMounts:
          - mountPath: /app/appsettings.yaml
            name: appsettings
            subPath: appsettings.yaml
        ports:
        - containerPort: {{ .Values.hub.api.port }}
        {{- if not .Values.hub.api.debugMode }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        {{- end }}
        env:
        - name: debug
          value: "{{ .Values.hub.api.debugMode }}"
        envFrom:
        - secretRef:
            name: hub
      initContainers:
      - name: db-migrations
        image: {{ .Values.hub.api.image }}
        imagePullPolicy: Always
        command: ["dotnet", "db-migrations.dll"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "125m"
        volumeMounts:
          - mountPath: /app/appsettings.yaml
            name: appsettings
            subPath: appsettings.yaml
        ports:
        - containerPort: {{ .Values.hub.api.port }}
        {{- if not (or (eq .Values.hub.api.debugMode true) (eq .Values.hub.dbMigrations.debugMode true)) }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        {{- end }}
        envFrom:
        - secretRef:
            name: hub
        env:
        - name: debug
          value: "{{ .Values.hub.dbMigrations.debugMode }}"
