kind: Secret
apiVersion: v1
metadata:
  name: hub
type: Opaque
stringData:
  postgresql__password: {{ .Values.postgresql.password }}
  mqtt__adminUsername: {{ .Values.mqtt.adminUsername }}
  mqtt__adminPassword: {{ .Values.mqtt.adminPassword  }}
  storage__key: {{ .Values.storage.key }}
  storage__secret: {{ .Values.storage.secret }}
  influxdb__user: {{ .Values.influxdb.user }}
  influxdb__password: {{ .Values.influxdb.password }}