apiVersion: v1
kind: Service
metadata:
  name: mqtt-controller
spec:
  selector:
    app: mqtt-controller
  ports:
  - port: {{ .Values.hub.mqttController.port }}
    targetPort: {{ .Values.hub.mqttController.port }}
