apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-controller
spec:
  selector:
    matchLabels:
      app: mqtt-controller
  template:
    metadata:
      labels:
        app: mqtt-controller
    spec: 
      serviceAccountName: cvops-hub
      replicas: 1
      volumes:
        - name: appsettings
          configMap:
            name: cvops-appsettings
            items:
              - key: appsettings.yaml
                path: appsettings.yaml
      {{- if not .Values.hub.mqttController.debugMode }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- end }}
      containers:
      - name: mqtt-controller
        image: {{ .Values.hub.mqttController.image }}
        imagePullPolicy: Always
        command: ["dotnet", "mqtt-controller.dll"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app/appsettings.yaml
            name: appsettings
            subPath: appsettings.yaml
            readOnly: true
        envFrom:
        - secretRef:
            name: hub
        env:
        - name: debug
          value: "{{ .Values.hub.mqttController.debugMode }}"
        ports:
        - containerPort: {{ .Values.hub.mqttController.port }}
        {{- if not .Values.hub.mqttController.debugMode }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        {{- end }}
         
