apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvops-mqtt-controller
spec:
  selector:
    matchLabels:
      app: cvops-mqtt-controller
  template:
    metadata:
      labels:
        app: cvops-mqtt-controller
    spec: 
      serviceAccountName: cvops-hub
      replicas: 2
      volumes:
        - name: appsettings
          configMap:
            name: cvops-appsettings
            items:
              - key: appsettings.yaml
                path: appsettings.yaml
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: cvops-mqtt-controller
        image: {{ .Values.hub.mqttController.image }}
        imagePullPolicy: Always
        {{- if .Values.hub.mqttController.debugMode }}
        command: ["dotnet", "debugger.dll"]
        {{- else }}
        command: ["dotnet", "mqtt-controller.dll"]
        {{- end }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app/appsettings.yaml
            name: appsettings
            subPath: appsettings.yaml
            readOnly: true
        ports:
        - containerPort: {{ .Values.hub.mqttController.port }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
         

