kind: Secret
apiVersion: v1
metadata:
  name: postgresql-credentials
type: Opaque
data:
  postgresql-password: <path:{{ .Values.secretStore.name }}#postgresql-password | base64encode>
  postgresql-username: <path:{{ .Values.secretStore.name }}#postgresql-username | base64encode>