kind: ConfigMap
apiVersion: v1
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: minio-svc.storage.svc.cluster.local:9000
      bucket: argo
      insecure: true
      accessKeySecret:
        name: minio-access
        key: rootUser
      secretKeySecret:
        name: minio-access
        key: rootPassword