kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo

bases:
- ../../base

resources:
- cvops-configmap.yaml

patchesStrategicMerge:
- artifact-repo.yaml
- persistence.yaml
- set-to-nodeport.yaml

patchesJson6902:
- target: 
    name: argo-server
    kind: Service
    version: v1
  path: set-port-numbers.yaml

