kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo-workflows

resources:
- ../../base
- cvops-configmap.yaml

patchesStrategicMerge:
- artifact-repo.yaml
- persistence.yaml

