kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo

bases:
- ../../base

resources:
- cvops-configmap.yaml
- test-pod.yaml

patchesStrategicMerge:
- artifact-repo.yaml
- persistence.yaml

