kind: ConfigMap
apiVersion: v1
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  persistence: |
    archive: true
    postgresql:
      host: postgresql.databases.svc.cluster.local
      port: 5432
      database: argo_workflows
      tableName: argo_workflows
      # the database secrets must be in the same namespace of the controller
      userNameSecret:
        name: argo-postgres-config
        key: username
      passwordSecret:
        name: argo-postgres-config
        key: password
      ssl: false
      # sslMode must be one of: disable, require, verify-ca, verify-full
      # you can find more information about those ssl options here: https://godoc.org/github.com/lib/pq
      sslMode: disable