apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: argo
spec:
  containers:
  - name: test-pod
    image: bitnami/postgresql:15.2.0-debian-11-r16
    command: ["/bin/bash"]
    env:
    - name: ARGO_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: argo-postgres-config
          key: password
    - name: ARGO_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: argo-postgres-config
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: postgresql-password
    - name: ARGO_DB_HOST
      valueFrom:
        configMapKeyRef:
          name: cvops-config
          key: postgresql-host