apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: argo
spec:
  containers:
  - name: test-pod
    image: ubuntu:22.04
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    env:
    - name: ARGO_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: argo-postgres-config
          key: password
    - name: ARGO_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: argo-postgres-config
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: postgresql-password
    - name: ARGO_DB_HOST
      valueFrom:
        configMapKeyRef:
          name: cvops-config
          key: postgresql-host