apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: mqtt
spec:
  template:
    spec:
      volumes:
      - name: api-key
        secret:  api-key
      containers:
        - name: emqx
          volumeMounts:
            - name: api-key
              mountPath: /opt/emqx/etc/api_keys.txt
              subPath: api_keys.txt