kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo-workflows

bases:
- ../base

resources:
- cvops-configmap.yaml

patchesStrategicMerge:
- artifact-repo.yaml
- persistence.yaml

