apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt-tcp-ingress
  namespace: mqtt
spec:
  entryPoints:
    - mqttssl
  routes:
    - match: HostSNI(`mqtt.local.cvops.io`)
      services:
        - name: emqx
          port: 1883
  tls: }{}