apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt-tcp-ingress
  namespace: mqtt
spec:
  entryPoints:
    - mqttssl
  routes:
    - match: HostSNI(`mqtt.{{ .Values.domain }}`)
      services:
        - name: emqx
          port: 8883
  tls: {}