apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt-tcp-ingress
  namespace: traefik
spec:
  entryPoints:
    - mqttssl
  routes:
    - match: HostSNI(`mqtt.local.cvops.io`)
      services:
        - name: emqx.mqtt.svc.cluster.local
          port: 8883
  tls:
    secretName: traefik-tls
    passthrough: false